spring.application.name=facushop
# --- Configuración de la Base de Datos Autónoma de Oracle ---

# 1. URL de Conexión (La obtienes de tu consola OCI)
#    Ejemplo: jdbc:oracle:thin:@nombrebasedatos_high?TNS_ADMIN=/ruta/a/tu/wallet
spring.datasource.url=jdbc:oracle:thin:@facushopdb_high?TNS_ADMIN=./wallet

# 2. Usuario y Contraseña (usualmente "ADMIN" y la pass que pusiste)
spring.datasource.username=ADMIN
spring.datasource.password=!Sdsdkl334[]

# 3. Driver de Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- Configuración de JPA (Hibernate) ---

# Esto es CLAVE: Le dice a Hibernate que cree o actualice las tablas (ej. "categories")
# basándose en tus clases @Entity (como Category.java) cuando la app arranque.
spring.jpa.hibernate.ddl-auto=update

application.jwt.secret-key=TU_LLAVE_SECRETA_EN_BASE64_AQUI

# Duración del token (ej. 24 horas)
# 86400000 milisegundos = 24 * 60 * 60 * 1000
application.jwt.expiration=86400000

# --- Configuración de OCI Object Storage ---
oci.config.path=C:\\Users\\facu_\\.oci\\config
oci.config.profile=DEFAULT
oci.bucket.name=facushop

