spring.application.name=facushop

# --- 1. BASE DE DATOS (Ruta Linux) ---
# Nota: La ruta apunta a donde copiamos el wallet en la VM
spring.datasource.url=jdbc:oracle:thin:@facushopdb_high?TNS_ADMIN=/home/ubuntu/facushop/wallet
spring.datasource.username=ADMIN
spring.datasource.password=!Sdsdkl334[]
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false 
# (En prod solemos apagar el log de SQL para no llenar el disco)

# --- 2. JWT (Mismas claves) ---
application.jwt.secret-key=TU_LLAVE_SECRETA_EN_BASE64_AQUI
application.jwt.expiration=86400000

# --- 3. OCI OBJECT STORAGE (Ruta Linux) ---
# Nota: La ruta apunta a la carpeta oculta .oci en el home del usuario ubuntu
oci.config.path=/home/ubuntu/.oci/config
oci.config.profile=DEFAULT
oci.bucket.name=facushop

# --- 4. MERCADO PAGO (Configuración de Producción) ---
mercadopago.access-token=APP_USR-5853519430828440-111016-1e48cbd47ee762af0431ac6fb4e6dbee-2980325687

# A) WEBHOOK (¡La URL estática de tu VM!)
# Usamos el puerto 8080 porque es donde escucha Java directamente
mercadopago.webhook-url=https://ff710f4c85cc.ngrok-free.app/api/webhooks/mercadopago

# B) REDIRECT URLS (¡OJO AQUÍ!)
# Estas son las URLs a las que vuelve el usuario en su navegador.
# DEBEN apuntar a tu Frontend en el Bucket, NO a localhost.
# (Si todavía no subiste el front al bucket, déjalas con la URL del bucket o espera al siguiente paso)
# Ejemplo: https://objectstorage.sa-saopaulo-1.oraclecloud.com/n/.../index.html
mercadopago.redirect.success-url=TU_URL_DEL_FRONTEND/pago-exitoso
mercadopago.redirect.failure-url=TU_URL_DEL_FRONTEND/pago-fallido
mercadopago.redirect.pending-url=TU_URL_DEL_FRONTEND/pago-pendiente

# --- CONFIGURACIÓN DE MONITOREO ---
# Habilitar todos los endpoints de monitoreo por HTTP
management.endpoints.web.exposure.include=health,info,prometheus
# Mostrar detalles de salud
management.endpoint.health.show-details=always