spring.application.name=facushop

# --- Base de Datos (Producción) ---
# Las credenciales y la URL (spring.datasource.*) serán inyectadas automáticamente 
# por las variables de entorno del docker-compose.yml
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- OCI OBJECT STORAGE (Ruta Linux) ---
oci.config.path=/home/ubuntu/.oci/config
oci.config.profile=DEFAULT
oci.bucket.name=facushop

# --- CONFIGURACIÓN DE MONITOREO ---\
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# (Las claves de JWT y MercadoPago también se inyectarán vía variables de entorno, 
# pero si tienes variables que no son secretas como las URLs de redirección, puedes dejarlas aquí)
mercadopago.redirect.success-url=https://tu-dominio.com/pago-exitoso
mercadopago.redirect.failure-url=https://tu-dominio.com/pago-fallido
mercadopago.redirect.pending-url=https://tu-dominio.com/pago-pendiente
mercadopago.webhook-url=https://tu-dominio.com/api/webhooks/mercadopago