spring.application.name=facushop
# --- Configuración de la Base de Datos Autónoma de Oracle ---

spring.datasource.url=jdbc:postgresql://localhost:5432/facushopdb
spring.datasource.username=postgres
spring.datasource.password=tu_password_local
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configuración de JPA (Hibernate) ---

# Esto es CLAVE: Le dice a Hibernate que cree o actualice las tablas (ej. "categories")
# basándose en tus clases @Entity (como Category.java) cuando la app arranque.
spring.jpa.hibernate.ddl-auto=update

application.jwt.secret-key=TU_LLAVE_SECRETA_EN_BASE64_AQUI

# Duración del token (ej. 24 horas)
# 86400000 milisegundos = 24 * 60 * 60 * 1000
application.jwt.expiration=86400000

# --- Configuración de OCI Object Storage ---
oci.config.path=C:\\Users\\facu_\\.oci\\config
oci.config.profile=DEFAULT
oci.bucket.name=facushop


# --- Configuración de Mercado Pago ---
mercadopago.access-token=APP_USR-5853519430828440-111016-1e48cbd47ee762af0431ac6fb4e6dbee-2980325687

# URLs a las que MP redirigirá al usuario después del pago
# (Pueden ser ficticias por ahora, pero las usará el frontend)
mercadopago.redirect.success-url=http://localhost:4200/pago-exitoso
mercadopago.redirect.failure-url=http://localhost:4200/pago-fallido
mercadopago.redirect.pending-url=http://localhost:4200/pago-pendiente

mercadopago.webhook-url=https://995ad60f3391.ngrok-free.app/api/webhooks/mercadopago

# --- CONFIGURACIÓN DE MONITOREO ---
# Habilitar todos los endpoints de monitoreo por HTTP
management.endpoints.web.exposure.include=health,info,prometheus
# Mostrar detalles de salud
management.endpoint.health.show-details=always

